[package]
name = "gruffed-analyzer"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
description.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
gruffed-core = { workspace = true }
gruffed-builder = { workspace = true }
gruffed-config = { workspace = true }
rayon = "1"
