[package]
name = "gruffed"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
description.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
keywords.workspace = true
categories.workspace = true

[[bin]]
name = "gruffed"
path = "src/main.rs"

[dependencies]
gruffed-core = { workspace = true }
gruffed-config = { workspace = true }
gruffed-builder = { workspace = true }
gruffed-analyzer = { workspace = true }
gruffed-console-reporter = { workspace = true }
clap = { version = "4", features = ["derive"] }
serde_json = "1"

[dev-dependencies]
serde_json = "1"
